name: Playwright Tests
on:
  push:
    branches: [ main ]
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.29.1-focal
      env:
        ADMIN_PASSWORD: Admin123
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo " Start the shopping store application"
          current_directory = $(pwd)
          echo $current_directory
          chmod +x ./playwright-practice/playwright-practice/shopping-store-linux-arm64 &
          current_directory = $(pwd)
          echo $current_directory
          echo " Install dependecies from lockfile"
          npm ci
          echo " Run playwright tests"
          npm run test:ci

